name: ReadyUp
version: "1.0"
main: dev.velocity71.ReadyUp.Main
api-version: 1.20
description: A Minecraft PaperMC plugin that only allows players to enter the world after the player count has reached a number.
author: Velocity71
